export const meta = {
  name: 'marginalia-live-verify',
  description: 'On the unRAID box: bring Marginalia up against a real Discord guild, verify every behaviour that could not be tested without a live connection, then run it as a supervised container',
  whenToUse:
    'Run this ONCE on the unRAID box that will host Marginalia permanently, after copying the repo to cache and putting a real DISCORD_TOKEN in deploy/.env. It is the companion to the offline build: that proved the logic with no Discord, this proves the integration. Pass args = {root, guild_id, channel_id, mode} where mode is "test" for a throwaway guild or "prod" for the real club server.',
  phases: [
    { title: 'Preflight', detail: 'image build, container env, full offline suite, secret sweep -- all before touching Discord' },
    { title: 'Connect', detail: 'gateway login, prove the members intent was actually granted, confirm command sync landed, prove the role hierarchy BEFORE any role write' },
    { title: 'Live checks', detail: 'strictly sequential: one agent drives the single bot at a time' },
    { title: 'Diagnose', detail: 'parallel read-only root-cause analysis of whatever failed' },
    { title: 'Ops', detail: 'watchdog from User Scripts, backup and restore, reboot survival' },
    { title: 'Report', detail: 'the honest live-verification ledger' },
  ],
}

// --------------------------------------------------------------------- inputs

const A = args || {}
const ROOT = A.root || '/mnt/cache/appdata/marginalia/src'
const DATA = A.data || '/mnt/cache/appdata/marginalia'
const DB = DATA + '/marginalia.db'
const NAME = 'marginalia'
const GUILD = A.guild_id || '<GUILD_ID from deploy/.env>'
const CHANNEL = A.channel_id || '<BOOK_CLUB_CHANNEL_ID from deploy/.env>'
const MODE = A.mode === 'prod' ? 'prod' : 'test'
// Run python in the container. There is no venv on an unRAID box and no pip.
const PYC = 'docker exec ' + NAME + ' python'

const REPORT = {
  type: 'object',
  additionalProperties: false,
  required: ['status', 'summary', 'evidence', 'blockers'],
  properties: {
    status: { type: 'string', enum: ['pass', 'partial', 'fail', 'blocked'] },
    summary: { type: 'string', description: 'What you did and what actually happened, 2-5 sentences' },
    evidence: {
      type: 'array',
      items: { type: 'string' },
      description: 'Exact command or action, then the real observed result. Never a prediction.',
    },
    blockers: {
      type: 'array',
      items: { type: 'string' },
      description: 'What stopped you, or what a human must do. Empty array if none.',
    },
  },
}

// The rules every agent inherits. The token is the whole reason this workflow
// runs on the server rather than on the laptop, so its handling is not optional.
const RULES = [
  '=== HARD RULES ===',
  '1. Work only inside ' + ROOT + ' and ' + DATA + '.',
  '2. THE TOKEN. ' + ROOT + '/deploy/.env contains a real Discord bot token. You',
  '   may read it only to confirm a variable is NON-EMPTY. NEVER print it, echo',
  '   it, put it in a report, write it to a log or a new file, or pass it on a',
  '   command line where it lands in shell history or the process list. If you',
  '   ever see it in output, treat that output as contaminated: do not include',
  '   it in your return value, and say in blockers that the token must be',
  '   rotated.',
  '3. THE DATABASE PATH. ' + DB + ' is a DIRECT cache-SSD path. Never move it,',
  '   copy it, or point anything at /mnt/user/... -- that is unRAID\'s shfs FUSE',
  '   layer, which does not give SQLite WAL the byte-range locking it needs and',
  '   is the documented cause of corrupt Plex/Sonarr databases. Read the',
  '   database READ-ONLY unless a step explicitly says otherwise, and use',
  '   `sqlite3 -readonly` or `file:...?mode=ro`, never a plain open.',
  '4. NEVER run git push, and never mutate a git remote.',
  '5. ' + (MODE === 'prod'
    ? 'MODE=prod: you are pointed at the REAL club server. Do not delete or'
    + '\n   rename anything a member created. Create only objects prefixed'
    + '\n   "verify-", and clean each one up before you finish. If a check would'
    + '\n   require destroying real club state, SKIP it and say so in blockers.'
    : 'MODE=test: this is a throwaway guild, so you may create and destroy'
    + '\n   freely -- but still clean up, because leftover roles and threads'
    + '\n   make the next run ambiguous.'),
  '6. Every claim in "evidence" must be something you OBSERVED. If you did not',
  '   run it, it is a blocker, not evidence. A false pass here is worse than a',
  '   reported gap, because it will be trusted for months.',
  '7. Rate limits: 50 req/s global, and 10,000 INVALID requests (401/403/429)',
  '   per 10 minutes ends in a Cloudflare IP ban on this host. Never retry a',
  '   403 or a 404, and never loop a failing call.',
  '8. Inclusive language everywhere: primary/main, replica/secondary,',
  '   allowlist, denylist.',
].join('\n')

const CONTEXT = [
  '=== CONTEXT ===',
  'Marginalia is a book club bot for ONE Discord channel, #florilegium. Python',
  '3.13 + discord.py 2.7.1, single process, SQLite via aiosqlite.',
  '',
  'IT RUNS IN DOCKER ON UNRAID. There is NO systemd unit: unRAID boots from USB',
  'and runs its OS from RAM, so /etc/systemd/system/ does not survive a reboot.',
  'Supervision is `restart: unless-stopped` in deploy/docker-compose.yml plus',
  'deploy/watchdog.sh on a */5 cron from the User Scripts plugin.',
  '',
  'It was built and unit-tested on a laptop that never held the token, so ALL',
  'logic is already proven offline. The integration surface has never run, and',
  'neither has the container. That is your entire job.',
  '',
  'Read these first; they are in the repo and they are authoritative:',
  '  docs/HANDOFF.md      the laptop-to-server boundary. Its "NEVER RUN" list',
  '                       is literally your work queue.',
  '  docs/HANDOFF.md       what is done, the residual LOW findings, and the',
  '                       numbers with receipts behind them.',
  '  docs/SPEC.md         this tree\'s design of record.',
  '  docs/PORTAL_SETUP.md what a human had to configure in the portal and the',
  '                       client, with what breaks if each step was skipped.',
  '  deploy/README.md     the unRAID ops runbook. AUTHORITATIVE on paths.',
  '  docs/ENV.md          MEASURED discord.py 2.7.1 facts. Its measurements',
  '                       override any assumption, including docstrings -- but',
  '                       its ARCHITECTURE is carried over from the first build',
  '                       and is stale (it says 22 modules and 30 commands).',
  '',
  'The shape of this tree, so you do not go looking for modules that were cut:',
  '  12 modules: timefmt, db, epub, config, schedule, library, reminders, bot,',
  '  __main__, and THREE cogs -- club, reading, quote.',
  '  library.py is the SINGLE choke point for all book text. There is no',
  '  spoiler.py, no search.py, no quotebudget.py, no metadata.py.',
  '  21 top-level commands / 22 runnable (/progress is a group with set+show).',
  '  8 organizer commands behind default_permissions(): /cycle-open,',
  '  /cycle-close, /ballot, /ballot-result, /schedule, /meeting, /ingest,',
  '  /purge_book.',
  '  There is no organizer role and no organizer env var.',
  '  Tables nomination_votes and reading_history do NOT exist.',
  '',
  'Known-measured facts that contradict the public docs -- trust these:',
  '- discord.Poll takes multiple=, NOT allow_multiselect= (hard TypeError).',
  '- discord.py enforces NONE of Poll\'s documented limits, so an over-long',
  '  question or an 11th answer fails as an HTTP 400 at send time, not locally.',
  '  club.build_poll validates first, which is the thing to verify.',
  '- Guild.create_scheduled_event has NO recurrence_rule parameter in 2.7.1.',
  '- Its docstring still says manage_events; creation needs create_events',
  '  (bit 44) since 2026-02-23. The docstring is stale.',
  '- TextChannel.create_thread defaults type to PRIVATE_THREAD. reading.py',
  '  passes public_thread explicitly; the OUTCOME is what you verify.',
  '- audioop-lts is a HARD requirement of discord.py on Python 3.13+.',
  '- Interactions and webhooks default allowed_mentions to users only, so a role',
  '  mention from an interaction pings NOBODY unless roles=[role] is explicit.',
  '- Cog loading FAILS FAST: bot.py setup_hook has no except around',
  '  load_extension. A boot that dies on an ExtensionError is DELIBERATE -- the',
  '  old behaviour logged a warning and synced a REDUCED command tree, leaving',
  '  eight commands absent from Discord with the bot looking green. Do not',
  '  "fix" it by restoring a try/except.',
  '',
  'Target guild: ' + GUILD,
  'Target channel (#florilegium): ' + CHANNEL,
  'Mode: ' + MODE,
  'Repo: ' + ROOT + '   Data: ' + DATA + '   DB: ' + DB,
].join('\n')

// ----------------------------------------------------------------- 1 PREFLIGHT

phase('Preflight')

const pre = await parallel([
  () => agent([RULES, CONTEXT, '',
    'TASK: build the image and prove the container environment is what the',
    'laptop verified. Touch Discord for nothing.',
    '',
    '1. THIS IMAGE HAS NEVER BEEN BUILT. There was no docker daemon on the',
    '   build machine, and the Dockerfile says so. You are its first real test.',
    '     cd ' + ROOT + '/deploy && docker compose build',
    '   The Dockerfile carries a BUILD-TIME SELF-CHECK that must pass: tzdata',
    '   really usable (January and July utcoffset for America/Chicago must',
    '   DIFFER), `import discord` works and reports 2.7.1, and the marginalia',
    '   modules import. Report the self-check line verbatim.',
    '2. If the tzdata assertion fails, STOP and report it as a blocker. The',
    '   entire scheduler is IANA-zone arithmetic; a stubbed zoneinfo database',
    '   fires reminders an hour wrong for half the year with nothing in the',
    '   logs. python:slim ships no tzdata, which is why the Dockerfile installs',
    '   it -- a failure here means the install did not take.',
    '3. If anything builds from source rather than installing a wheel, report',
    '   it: it means a wheel is missing for this platform.',
    '4. Bring it up: docker compose up -d, then docker logs ' + NAME + '.',
    '5. Inside the container, verify the bundled sqlite3 has FTS5 compiled in,',
    '   and that bm25() and snippet() are callable through aiosqlite',
    '   specifically:  ' + PYC + ' -c "..."',
    '6. Confirm the bind mount and the path story agree, and DO NOT change',
    '   them: docker-compose.yml mounts ' + DATA + ':/data and sets',
    '   MARGINALIA_DB=/data/marginalia.db in `environment:`, which OVERRIDES',
    '   env_file. Report the effective MARGINALIA_DB inside the container and',
    '   confirm it resolves to the same inode as ' + DB + ' on the host.',
    '7. Confirm ' + DATA + ' is on the CACHE pool and not on /mnt/user. Report',
    '   the real device. If any part of this path traverses shfs, that is a',
    '   blocker, not a preference: it is the documented cause of SQLite',
    '   corruption on unRAID and it drags the parity array awake for every WAL',
    '   write.',
    '8. Confirm ' + DATA + ' is owned by 99:100 (unRAID nobody:users), which is',
    '   the fixed uid the image runs as. The image deliberately does NOT honour',
    '   PUID/PGID.',
    '9. Confirm there is no `ports:` stanza. The gateway connection is OUTBOUND;',
    '   nothing listens. Do not add one.',
  ].join('\n'), { label: 'pre:image+container', phase: 'Preflight', schema: REPORT }),

  () => agent([RULES, CONTEXT, '',
    'TASK: run the ENTIRE offline test suite here and report the real result.',
    'This is the gate: if the suite is red on this box, the live checks must not',
    'run at all, because every Discord object they create would be built on a',
    'broken tree and would have to be torn down again.',
    '',
    '1. Run it in the container so it uses the same interpreter and the same',
    '   libsqlite the bot will use. The runtime image has no pytest, so install',
    '   the dev pins into a throwaway layer or a temporary container -- do NOT',
    '   add them to the running bot container:',
    '     docker run --rm -v ' + ROOT + ':/src -w /src marginalia:latest \\',
    '       sh -c "pip install -q -r requirements-dev.txt && python -m pytest -q"',
    '   Paste the real summary line. Do not fix anything -- you are measuring.',
    '   If it is red, list exactly which tests fail and why.',
    '2. Run the linter the same way: ruff check /src',
    '3. Confirm the PLATFORM-SENSITIVE tests specifically pass here and not just',
    '   on macOS. A different libsqlite or a different tzdata vintage is the',
    '   most likely laptop-green / server-red divergence:',
    '   - tests/test_timefmt.py and test_schedule.py (DST / zoneinfo)',
    '   - tests/test_db.py (WAL, FTS5 external content and its triggers)',
    '   - tests/test_library.py (FTS5 retrieval and query sanitization)',
    '   Call out any test that passes on one platform and not the other.',
    '4. Confirm tests/test_invariants.py passes in full -- in particular',
    '   invariant 7, which imports every module in a subprocess with env={}.',
    '   That is the guard that keeps this tree testable with no token.',
    '5. Confirm marginalia/timefmt.py and marginalia/schedule.py still do NOT',
    '   import discord, and that schedule.py touches no database. That purity is',
    '   deliberate and load-bearing (invariant 6 asserts it; confirm it ran).',
    '6. Report the exact counts you saw. docs/HANDOFF.md records the number as a',
    '   moving target because three agents were editing the tree when it was',
    '   written -- your number is the current truth, so state it plainly rather',
    '   than reconciling it with the document.',
  ].join('\n'), { label: 'pre:suite', phase: 'Preflight', schema: REPORT }),

  () => agent([RULES, CONTEXT, '',
    'TASK: validate configuration and prove no secret is anywhere it should not',
    'be. Remember rule 2 -- confirm presence, never print a value.',
    '',
    '1. Confirm ' + ROOT + '/deploy/.env exists and its permissions are 0600.',
    '   Fix them to 0600 if looser, and report what they were.',
    '2. Confirm the FOUR required variables are present and NON-EMPTY:',
    '   DISCORD_TOKEN, GUILD_ID, BOOK_CLUB_CHANNEL_ID, MARGINALIA_DB. Report',
    '   NAMES only -- never a value, never even a prefix or a length for the',
    '   token. Note that MARGINALIA_DB in .env is IGNORED on unRAID because',
    '   compose sets it in `environment:`; that is correct, not a bug.',
    '3. Confirm .env does NOT still carry OPENLIBRARY_USER_AGENT or',
    '   ANTHROPIC_API_KEY. Both were deleted from .env.example because neither',
    '   feature exists in this build (no HTTP call in cogs/club.py, no LLM',
    '   layer). Harmless if present, but report it so the file gets cleaned.',
    '4. Confirm the config loader accepts the real environment: load it through',
    '   marginalia.config inside the container and confirm it validates. Then',
    '   confirm repr() and str() of the Config object REDACT the token --',
    '   actually call them and check. That is the guard that stops the token',
    '   reaching a log.',
    '5. Confirm the failure path is loud and safe: run the module with an empty',
    '   environment and confirm exit code 2 and a message naming EVERY missing',
    '   variable at once, quoting no value.',
    '6. SECRET SWEEP. Grep the whole tree (excluding .venv and .git) for',
    '   anything token-shaped, an API key, or a password. Confirm .env is',
    '   gitignored: git check-ignore -v deploy/.env. Confirm git ls-files does',
    '   NOT list any .env, any *.db, or any *.epub. If this is not a git clone,',
    '   say so instead of inventing a result.',
    '7. Run the migration ladder against the REAL configured database path.',
    '   Confirm PRAGMA user_version reaches the expected value, that WAL is on,',
    '   and that the -wal sidecar appears NEXT TO the db in ' + DATA + '.',
    '   Report the final schema version and the table count -- expect 12 tables',
    '   plus the para_fts virtual table.',
    '8. Confirm no .db file was accidentally committed, and that ' + DATA + ' is',
    '   writable by uid 99.',
  ].join('\n'), { label: 'pre:config+db', phase: 'Preflight', schema: REPORT }),
])

const preOk = pre.filter(Boolean)
const preflightFailed = preOk.some((r) => r && (r.status === 'fail' || r.status === 'blocked'))

if (preflightFailed) {
  log('PREFLIGHT FAILED -- stopping before any Discord object is created. ' +
      'Fix the build first; nothing below is meaningful on a broken tree.')
  return {
    halted_at: 'Preflight',
    reason: 'One or more preflight agents reported fail/blocked. Live checks ' +
            'were deliberately skipped so that no Discord state was created ' +
            'against a broken build.',
    preflight: preOk,
  }
}

log('Preflight green. Connecting to Discord.')

// ------------------------------------------------------------------- 2 CONNECT

phase('Connect')

const connect = await agent([RULES, CONTEXT, '',
  'TASK: bring the bot up against the real guild and prove the things that are',
  'ONLY observable with a live gateway. You are the first agent to use the',
  'token. Work carefully and sequentially.',
  '',
  '1. Start it in the FOREGROUND with output captured, so a first boot is',
  '   debuggable:  cd ' + ROOT + '/deploy && docker compose up   (no -d).',
  '   Give it time to finish setup_hook.',
  '2. Confirm it authenticated: the ready log line, the bot user id, and that it',
  '   sees guild ' + GUILD + '.',
  '   If it EXITED on an ExtensionError traceback instead, that is the fail-fast',
  '   loader doing its job -- a cog failed to import. Report the traceback as a',
  '   blocker and do NOT restore a try/except to get past it.',
  '3. PROVE THE MEMBERS INTENT IS ACTUALLY GRANTED. Highest-value check in this',
  '   phase, because the failure is silent. Fetch the guild and assert',
  '   len(guild.members) > 1. If it reads 0 or 1, the Server Members Intent',
  '   toggle is OFF in the portal -- there will be no error anywhere, the roster',
  '   will simply always read empty, and /cycle-close will silently strip the',
  '   role from nobody because guild.get_member() returns None for everyone.',
  '   Report the real count.',
  '4. Confirm the bot did NOT request message_content or presences: report which',
  '   intent bits it connected with. An unapproved privileged intent closes the',
  '   gateway with 4014 and an invalid one with 4013; if you saw either, that is',
  '   your answer. discord.py does not reconnect after either -- exiting is',
  '   intentional.',
  '5. Confirm the guild-scoped command sync landed. List the registered',
  '   application commands and report the exact count and names. Expect 21',
  '   top-level (22 runnable: /progress is a group with set and show). A REDUCED',
  '   count now means a genuinely partial tree, which the fail-fast loader is',
  '   supposed to make impossible -- report it loudly. Guild-scoped commands',
  '   appear instantly, so absence is a sync bug, not propagation latency. The',
  '   cap is 200 command creates per day per guild, so do NOT loop the sync.',
  '6. Confirm the bot sees #florilegium (' + CHANNEL + ') and that its EFFECTIVE',
  '   permissions there include send_messages, create_public_threads,',
  '   send_messages_in_threads, read_message_history and send_polls. Report the',
  '   computed permission integer. A channel-level overwrite silently beats the',
  '   guild-level grant, so check the effective value, not the role page.',
  '   read_message_history and send_polls are NOT in the invite integer -- they',
  '   are normally inherited from @everyone, which is exactly why they need',
  '   checking here.',
  '7. VERIFY THE ROLE HIERARCHY BEFORE ANY ROLE WORK IS ATTEMPTED. Compare the',
  '   Marginalia integration role\'s position against the highest role it must',
  '   manage. If it is not strictly above, STOP and report a blocker naming the',
  '   exact fix: Server Settings, Roles, drag Marginalia above every',
  '   "Marginalia YYYY-MM" cohort role. Do not attempt a role assignment you',
  '   already know will 403 -- failed attempts count toward the invalid-request',
  '   ban, and no permission (not even Administrator) overrides position.',
  '8. Shut it down cleanly and confirm the database closed.',
  '',
  'Report the exact log lines you observed as evidence. If any of steps 3, 5 or',
  '7 fail, mark status fail and put the human fix in blockers -- every live check',
  'below depends on all three.',
].join('\n'), { label: 'connect:gateway+intents+sync+hierarchy', phase: 'Connect', schema: REPORT })

if (!connect || connect.status === 'fail' || connect.status === 'blocked') {
  log('CONNECT FAILED -- a human must fix the portal or role configuration ' +
      'before live checks can run. Stopping.')
  return {
    halted_at: 'Connect',
    reason: 'Gateway/intents/sync/hierarchy verification did not pass.',
    preflight: preOk,
    connect,
  }
}

log('Connected and configured correctly. Running live checks SEQUENTIALLY.')

// --------------------------------------------------------------- 3 LIVE CHECKS

phase('Live checks')

// These MUST be sequential. There is exactly one bot process and one guild, so
// parallel agents would collide on shared state and share one rate-limit bucket
// -- gaining nothing and risking 429s. A plain awaited for-loop is the correct
// primitive here, not pipeline() or parallel().
const CHECKS = [
  {
    key: 'cycle-role-lifecycle',
    prompt: [
      'Verify the month-scoped cycle lifecycle end to end, live.',
      '',
      'THE CHANNEL GUARD FIRST, because it is new and cheap:',
      '- Run /cycle-open in a channel that is NOT #florilegium. Confirm it',
      '  refuses ephemerally, naming the configured channel, AND that NO role',
      '  was created and no cohorts row was written. The guard sits before',
      '  create_role precisely so a misfire leaves no orphan role -- verify the',
      '  absence, do not just read the refusal.',
      '- Then run it INSIDE #florilegium as the positive control. Without both',
      '  halves an always-refusing bug is indistinguishable from a working',
      '  guard.',
      '',
      'Then the lifecycle, with a "verify-" prefixed cycle:',
      '- Confirm the role is created with mentionable=True.',
      '- Opt a member in via the button and confirm the role is actually',
      '  assigned. Then confirm cohort_members mirrors it in the database.',
      '- /leave and confirm both sides come back consistent.',
      '- /cycle-close and confirm the role is stripped from every member while',
      '  the cohort_members ROWS SURVIVE. That combination is what "subscribed',
      '  for that month only" means mechanically, and keeping the rows is what',
      '  /library reads later -- verify BOTH halves, not just the strip.',
      '- Confirm a double-join is idempotent rather than erroring.',
      '- Confirm the role calls went out SEQUENTIALLY, not gathered. One',
      '  rate-limit bucket; concurrency buys nothing and invites 429s.',
      'Clean up the verify- role and cycle when done.',
    ].join('\n'),
  },
  {
    key: 'persistent-button-restart',
    prompt: [
      'Verify the opt-in button SURVIVES A RESTART. This is the check most bots',
      'fail, and it fails silently until a real member clicks a month later.',
      '',
      '- Post the opt-in message. Click the button; confirm it works.',
      '- Fully stop the container: docker stop ' + NAME,
      '- Start it again: docker start ' + NAME,
      '- Click the SAME button on the SAME old message.',
      '- If Discord shows "This interaction failed", the DynamicItem was not',
      '  re-registered. Diagnose which of the three causes it is:',
      '  add_dynamic_items missing from setup_hook, an INSTANCE passed where the',
      '  CLASS is required (issubclass TypeError), or a custom_id that does not',
      '  match the template r"mgl:join:(?P<cohort>\\d+)".',
      '- Note that "This interaction failed" is ALSO what an unhandled callback',
      '  exception and a blown 3-second deadline produce. A registration failure',
      '  logs NOTHING, because the process never saw a matching handler -- that',
      '  is how you tell them apart. Check the log before concluding.',
      'This check requires a real container restart -- do not simulate it.',
    ].join('\n'),
  },
  {
    key: 'role-ping-both-paths',
    prompt: [
      'Verify a role mention ACTUALLY NOTIFIES, from BOTH code paths. This is',
      'the single most likely silent failure in the project.',
      '',
      'Regular messages parse mentions permissively, but interactions and',
      'webhooks default allowed_mentions to users only -- so a role mention sent',
      'from an interaction handler renders as blue text and pings NOBODY. It',
      'looks completely correct in the channel.',
      '',
      '- Send a role mention from the POLLER path (bot.deliver). Confirm a real',
      '  notification arrives -- badge, sound -- not merely styled text.',
      '- Send one from an INTERACTION path (/cycle-open or /roster, which go',
      '  through club._reply). Confirm the same.',
      '- Confirm both call sites pass an explicit AllowedMentions(everyone=',
      '  False, users=False, roles=[role]).',
      '- Confirm the bot CANNOT ping everyone: verify it lacks MENTION_EVERYONE',
      '  (bit 17), so that guarantee is STRUCTURAL rather than a code',
      '  convention. Do not add the bit to make anything work.',
      'You need a second account to observe a notification reliably.',
    ].join('\n'),
  },
  {
    key: 'timestamps-render',
    prompt: [
      'Verify Discord timestamp rendering, which is the one hard user',
      'requirement (members span timezones).',
      '',
      '- Post a message through timefmt.when() -- /next or /schedule -- and',
      '  confirm it renders as a localized absolute time plus a relative time,',
      '  NOT as literal "<t:...>" text.',
      '- Confirm the value is in SECONDS: a milliseconds bug renders as roughly',
      '  the year 55000, which is unmistakable.',
      '- RESOLVE THE OPEN QUESTION: test whether timestamp markup renders inside',
      '  an EMBED title, description, field name, field value, and footer. This',
      '  is undocumented and widely believed not to work in some slots. Report',
      '  slot by slot what actually happened -- this answer should be written',
      '  back into docs/ENV.md.',
      '- Do the same for spoiler bars inside embed slots.',
      '- A two-human two-timezone confirmation cannot be done by an agent. Note',
      '  it in blockers as a human task.',
    ].join('\n'),
  },
  {
    key: 'reminder-restart-survival',
    prompt: [
      'Verify the reminder engine against real time and real restarts. This is',
      'the core of the product: the offline tests proved the logic, this proves',
      'the wiring.',
      '',
      '- Insert a checkpoint a few minutes out with short-interval reminders.',
      '  Confirm they fire, to the right role, with the right wording. The five',
      '  kinds are unlock, T-24h, T-1h, meeting-T-24h, meeting-T-1h.',
      '- STOP the container. Wait past a due time. START it. Confirm the',
      '  reminder fires LATE but within grace, rather than never.',
      '- Stop it, wait past due + grace, restart. Confirm the row is marked',
      '  skipped and NOT sent.',
      '- Confirm an unlock reminder, which carries INFINITE grace, fires no',
      '  matter how late.',
      '- docker kill mid-send, then confirm reap() returns the row to pending',
      '  and it delivers exactly once, not twice.',
      '- Run /schedule twice and confirm UNIQUE(checkpoint_id, kind) prevents',
      '  duplicate reminders.',
      '- Confirm the heartbeat row advances on EVERY tick including zero-work',
      '  ticks. That row is the only thing that distinguishes a live scheduler',
      '  from a live process, and it is what the watchdog reads.',
      'Use short intervals so this is minutes, not hours. Clean up after.',
    ].join('\n'),
  },
  {
    key: 'meeting-anchor',
    prompt: [
      'Verify /meeting -- the wrap-up anchor. This carried a CRITICAL judge',
      'finding whose fix has only ever been proven offline.',
      '',
      '- Run /meeting to set the cycle wrap-up. Confirm the anchor checkpoint',
      '  and its TWO reminders (meeting-T-24h, meeting-T-1h) exist.',
      '- THE CRITICAL ONE: now re-run /schedule. Confirm the anchor\'s two',
      '  pending reminders STILL EXIST. The purge is scoped with',
      '  AND is_meeting_anchor = 0; without it, an ordinary /schedule re-run',
      '  silently deleted the wrap-up reminders and nobody found out until the',
      '  meeting did not get announced.',
      '- Do it in BOTH orders: /meeting then /schedule, and /schedule then',
      '  /meeting then /schedule again. Both were the proven triggers.',
      '- Confirm the anchor does NOT raise the spoiler ceiling: ask for content',
      '  past the last weekly checkpoint and confirm refusal. The anchor carries',
      '  chapter_ceiling = 0 and ceiling() takes MAX over due checkpoints, so 0',
      '  cannot raise it -- verify the behaviour, not the reasoning.',
      '- Confirm the anchor does not corrupt /pace or the reported unit: run a',
      '  by=pages plan with an anchor present and confirm the unit reads "page".',
      '- Confirm the anchor delivers through the same bot.deliver with no',
      '  special branch.',
    ].join('\n'),
  },
  {
    key: 'threads-public',
    prompt: [
      'Verify per-checkpoint threads come out PUBLIC and correctly gated.',
      '',
      '- Trigger an unlock. Confirm a thread is created and is actually PUBLIC',
      '  and visible to a non-privileged member. The API defaults this to',
      '  PRIVATE_THREAD and the library source confirms it, so an invisible',
      '  thread is the EXPECTED failure here.',
      '- Confirm auto_archive_duration is 10080. A shorter value makes a monthly',
      '  club\'s thread vanish mid-week.',
      '- Confirm a channel_policy row was written pinning that thread\'s',
      '  max_chapter, then confirm the gate HONOURS it: ask from inside the',
      '  thread for content beyond that chapter and confirm refusal. Then ask',
      '  for something within it and confirm it serves -- the positive control',
      '  is what distinguishes a working gate from an always-empty bug.',
      '- Confirm the CROSS-BOOK leak is closed: from a checkpoint thread of book',
      '  A, ask for book B and confirm fail-closed refusal, while book A at that',
      '  chapter still serves in the same thread.',
      '- Confirm unlocking the same checkpoint twice does not create a second',
      '  thread.',
      '- Confirm a thread pinned BEFORE the book was ingested gets re-synced by',
      '  a later /schedule rather than staying frozen at max_chapter = 0.',
      'Clean up verify- threads.',
    ].join('\n'),
  },
  {
    key: 'scheduled-events',
    prompt: [
      'Verify native Scheduled Events, where the permission story is known to be',
      'stale in the library docs.',
      '',
      '- /schedule creates guild scheduled events (reading.py). Confirm creation',
      '  succeeds and report which permission actually allowed it: the docstring',
      '  claims manage_events, but the real requirement since 2026-02-23 is',
      '  create_events (bit 44), which is what the invite granted. Settle it',
      '  empirically and report exactly what happened.',
      '- Confirm the events appear in the guild Events tab with the right times.',
      '- Confirm the event-count guard behaves before the 100 SCHEDULED-or-ACTIVE',
      '  cap. Do NOT actually create 100 events.',
      '- Confirm no code path passes recurrence_rule, since the parameter does',
      '  not exist in discord.py 2.7.1 -- the monthly cadence comes from our own',
      '  scheduler, not from Discord.',
      'Delete the verify- events when done.',
    ].join('\n'),
  },
  {
    key: 'ballot-poll',
    prompt: [
      'Verify nomination and the native Poll, where the build found real API',
      'discrepancies that only fail at send time.',
      '',
      '- Submit a nomination through /nominate\'s modal. Confirm the row and the',
      '  reply. Note the modal is one interaction and needs no message_content',
      '  intent.',
      '- /ballot creates a Poll from the shortlist. CONFIRM THE KEYWORD IS',
      '  multiple= -- allow_multiselect= is a hard TypeError in 2.7.1.',
      '- Confirm approval voting works: a voter can select more than one.',
      '- THE IMPORTANT ONE: discord.py enforces NONE of Poll\'s documented limits',
      '  locally, so verify OUR validation catches them BEFORE the send. Attempt',
      '  an 11th answer, an over-long question, an over-long answer, and a',
      '  duration over 168 hours, and confirm club.build_poll refuses each one',
      '  CLIENT-SIDE rather than eating an opaque HTTP 400 from Discord.',
      '- /ballot-result: confirm it waits for is_finalized() before reading',
      '  counts, and that an ABSENT results field is treated as unknown rather',
      '  than zero.',
      '- Confirm the answer-id-to-nomination join is right: add_answer assigns',
      '  ids 1..n in insertion order, so the join is positional.',
      '- Confirm the anti-repeat filter excludes books an ended cohort already',
      '  read.',
      '- Confirm a TIE is reported rather than silently broken.',
    ].join('\n'),
  },
  {
    key: 'library-spoiler-live',
    prompt: [
      'Verify the ebook path and, above all, the spoiler gate under real',
      'conditions. Treat this as the security check of the deployment.',
      'library.py is the SINGLE choke point for all book text; there is no',
      'spoiler.py in this build.',
      '',
      '- /ingest a public-domain EPUB (Standard Ebooks or Project Gutenberg).',
      '  It takes a FILESYSTEM PATH inside the container, never an attachment.',
      '  Confirm chapter detection matches the real book, and confirm the SOURCE',
      '  FILE IS DELETED after ingest.',
      '- Confirm /quote returns VERBATIM text with the full locator.',
      '- Set a ceiling below the book length. Ask for a phrase that appears only',
      '  beyond it and confirm refusal. Then ask for one BELOW it and confirm',
      '  success -- without that positive control, an always-empty bug looks',
      '  identical to a working gate.',
      '- Confirm every book-text reply is EPHEMERAL, and confirm EMPIRICALLY',
      '  that an ephemeral response generates NO push notification for another',
      '  member. That property is the actual defence against a mobile',
      '  lock-screen spoiler leak; spoiler bars do not provide it, because a',
      '  notification preview renders the raw bars.',
      '- Confirm the refusal text leaks NOTHING: not the query, not a chapter',
      '  title beyond the ceiling, not a count of matches beyond it. Confirm two',
      '  different refusals are textually IDENTICAL where they should be -- a',
      '  refusal that differs by reason is an oracle.',
      '- Confirm the quote budget engages: the 2%-per-30-days cap, the per-quote',
      '  word cap, the 3-per-response cap, and abutment/whole-chapter refusal.',
      '  Confirm the refusal offers locators only.',
      '- Confirm literal || in the source text survives escaped, so the spoiler',
      '  bars are never left open.',
      '- Confirm /ingest refuses a DRM-protected EPUB with a clear message and no',
      '  traceback, while a FONT-OBFUSCATED one still parses. Those two look the',
      '  same in the container and must not be conflated.',
      '- Confirm /purge_book removes exactly that book and nothing else.',
      '- Confirm /find returns citations only and spends no allowance.',
    ].join('\n'),
  },
  {
    key: 'progress-and-privacy',
    prompt: [
      'Verify the self-only reading surface, including /progress show, which is',
      'new and appears in no earlier document.',
      '',
      '- /progress set, then /progress show. Confirm the history is paginated',
      '  and that the page footer arithmetic is right at the boundaries.',
      '- Confirm /progress show, /pace, /mystats and /dnf are ALL ephemeral,',
      '  self-only and never attributed publicly. There are deliberately no',
      '  leaderboards, streaks, rankings or per-member nagging -- confirm none',
      '  leaked in.',
      '- Confirm /dnf records privately and announces nothing.',
      '- Confirm a lower progress number is accepted (people re-read and',
      '  restart).',
      '- Confirm /library lists what the club has read, paginated, and that it',
      '  still lists a book whose cohort has closed -- closing strips the role',
      '  but KEEPS the cohort_members rows, which is what makes this work.',
      '- Confirm no reply here carries a real ping: allowed_mentions must be',
      '  none on everything self-only.',
    ].join('\n'),
  },
]

const live = []
for (let i = 0; i < CHECKS.length; i++) {
  const c = CHECKS[i]
  const r = await agent([RULES, CONTEXT, '',
    'You are live check ' + (i + 1) + ' of ' + CHECKS.length + ': "' + c.key + '".',
    '',
    'You are the ONLY agent touching Discord right now -- the checks run',
    'strictly one at a time because there is one bot and one guild. Do your',
    'work, clean up every object you created, and leave the guild in the state',
    'you found it.',
    '',
    c.prompt,
    '',
    'METHOD: do the thing, OBSERVE the result, report what you actually saw.',
    'If something fails, do NOT spend the run fixing it -- capture precise',
    'diagnostic detail (the exact error, the close code, the HTTP status, the',
    'log line, the relevant file and line) and move on. A parallel diagnosis',
    'phase runs afterwards specifically to root-cause failures, and it works',
    'better from good evidence than from a half-attempted fix.',
    '',
    'Set status pass only if you verified every bullet. Use partial honestly.',
  ].join('\n'), { label: 'live:' + c.key, phase: 'Live checks', schema: REPORT })

  live.push({ key: c.key, result: r })
  log('live ' + (i + 1) + '/' + CHECKS.length + ' ' + c.key + ' -> ' +
      (r ? r.status : 'ERRORED'))
}

// ------------------------------------------------------------------ 4 DIAGNOSE

const failed = live.filter((x) => !x.result || x.result.status !== 'pass')

let diagnoses = []
if (failed.length) {
  phase('Diagnose')
  log(failed.length + ' of ' + CHECKS.length + ' live checks did not fully ' +
      'pass. Fanning out read-only root-cause analysis.')

  // Safe to parallelize: diagnosis is read-only. Nothing here touches Discord.
  diagnoses = (await parallel(failed.map((f) => () =>
    agent([RULES, CONTEXT, '',
      'TASK: root-cause the live check "' + f.key + '", which did not pass.',
      '',
      'What the live agent observed:',
      JSON.stringify(f.result, null, 2),
      '',
      'You are READ-ONLY with respect to Discord -- make no API calls, create',
      'nothing, and do not start the bot. Other diagnosis agents are running in',
      'parallel and the guild must stay untouched. Read the database READ-ONLY.',
      '',
      'Work from the code, the container logs, docs/SPEC.md, docs/ENV.md and',
      'docs/HANDOFF.md, and produce a specific diagnosis:',
      '1. Is this a CODE defect, a PORTAL/permission misconfiguration, a',
      '   GUILD-state problem, a CONTAINER/HOST problem, or a wrong assumption',
      '   baked into the build? Say which, and how you know.',
      '2. Name the exact file and line, or the exact portal/client setting, or',
      '   the exact compose/Dockerfile line.',
      '3. Give the minimal fix. If it is a code fix, write the patch as a diff',
      '   in your report -- but do NOT apply it, because the suite would need',
      '   re-running and the live check repeating, and that is the operator\'s',
      '   decision.',
      '4. Check docs/HANDOFF.md section 6 first: this may be a KNOWN residual LOW',
      '   finding rather than a new defect. Say so if it is.',
      '5. Say whether this blocks going live or is cosmetic.',
      '6. If the root cause contradicts docs/SPEC.md or docs/ENV.md, say so',
      '   explicitly -- a measured correction is the most valuable output you',
      '   can produce.',
      '',
      'Put the diagnosis in summary and the fix in blockers.',
    ].join('\n'), { label: 'diag:' + f.key, phase: 'Diagnose', schema: REPORT })))).filter(Boolean)
}

// ----------------------------------------------------------------------- 5 OPS

const liveBlocking = failed.filter((f) => f.result && f.result.status === 'fail')

let ops = null
if (liveBlocking.length) {
  log('Skipping the Ops phase: ' + liveBlocking.length + ' live check(s) hard-' +
      'failed, so wiring up restart:unless-stopped and a watchdog would only ' +
      'make a broken bot fail forever on a schedule.')
} else {
  phase('Ops')

  ops = await agent([RULES, CONTEXT, '',
    'TASK: make Marginalia permanent and prove the operational safety net',
    'actually works. NOTHING in deploy/ has ever executed -- it was written on a',
    'macOS laptop with no docker daemon, so you are its first real test.',
    '',
    'THERE IS NO SYSTEMD UNIT AND YOU MUST NOT CREATE ONE. unRAID boots from USB',
    'and runs its OS from RAM: anything you write to /etc/systemd/system/ is',
    'gone after a reboot. Supervision is Docker plus the User Scripts plugin.',
    '',
    '1. Bring it up detached: cd ' + ROOT + '/deploy && docker compose up -d.',
    '   Confirm `restart: unless-stopped` is in effect (docker inspect the',
    '   RestartPolicy) and that the bot connected.',
    '2. PROVE THE RESTART PATH: docker kill ' + NAME + '. Confirm Docker brings',
    '   it back, the bot reconnects, and a pending reminder still fires. Report',
    '   the observed delay.',
    '3. PROVE THE WATCHDOG, which exists for the failure mode that matters most:',
    '   PROCESS LIVENESS IS NOT SCHEDULER LIVENESS. The reminder loop can die',
    '   while the container stays up, Discord stays connected and slash commands',
    '   keep working -- and no reminder is ever sent again. `docker ps` cannot',
    '   see this. The heartbeat row is the only signal that can.',
    '   - Install deploy/watchdog.sh: Settings -> User Scripts -> Add New Script',
    '     -> name it marginalia-watchdog -> paste the file -> schedule Custom',
    '     "*/5 * * * *".',
    '   - Stall or kill the poller task WITHOUT killing the container. Confirm',
    '     the heartbeat goes stale and the watchdog restarts the container. On',
    '     the laptop only the detection half was even testable -- you can',
    '     finally test the restart half.',
    '   - Confirm it opens the database READ-ONLY so it can never corrupt it.',
    '   - Confirm the 600s STALE threshold is respected and understand why it is',
    '     generous: bot.py deliberately STOPS restarting its own loop after 6',
    '     consecutive failures (5+10+20+40+60 = 135s of backoff), so the',
    '     heartbeat is allowed to go stale and prove the scheduler is genuinely',
    '     dead. A shorter threshold would just fight the backoff.',
    '   - KNOWN LOW FINDING (docs/HANDOFF.md L-4): `docker restart` starts a',
    '     STOPPED container, so after a deliberate `docker compose down` the',
    '     watchdog will resurrect the bot at the next cron run past 600s. Check',
    '     whether a State.Running guard has landed; if not, report it and give',
    '     the operator the one-line fix rather than being surprised by it later.',
    '4. Give the operator the ONE-LINER that distinguishes SCHEDULING from merely',
    '   RUNNING, and confirm you actually ran it:',
    '     sqlite3 -readonly ' + DB + ' \\',
    '       "SELECT strftime(\'%s\',\'now\') - beat_at, tick_count, detail \\',
    '          FROM heartbeat WHERE name=\'reminders\'"',
    '   Under 60 is healthy (the loop ticks every 30s). Over ~600 means the',
    '   scheduler is dead no matter what docker ps says.',
    '5. PROVE BACKUP AND RESTORE. Run the sqlite3 .backup command from',
    '   deploy/README.md while the bot is running and writing, and confirm it',
    '   produces a CONSISTENT snapshot. It must be .backup and not cp: a copy',
    '   reads the file over a non-zero span so it can capture pages from before',
    '   and after a concurrent write, and in WAL mode the committed state is',
    '   split between the db and its -wal. Then ACTUALLY RESTORE it to a scratch',
    '   path and confirm the data is intact -- an untested backup is not a',
    '   backup. Install a schedule (User Scripts is fine).',
    '   The backup DESTINATION on /mnt/user is fine; it is a plain file nothing',
    '   locks. The LIVE database must stay on ' + DATA + '.',
    '6. PROVE REBOOT SURVIVAL, which matters more here than on a normal box',
    '   because unRAID rebuilds its OS from the USB stick every boot. Reboot if',
    '   you are permitted. Confirm the container comes back by itself, the bot',
    '   reconnects, the User Scripts cron entry survived, and a reminder that',
    '   came due during the outage fires late-within-grace rather than never.',
    '   If you may not reboot, say so in blockers -- do not claim it untested.',
    '7. Confirm NTP is running on the host. Note that the polling design',
    '   tolerates drift because a "due_at <= now" query self-heals when the clock',
    '   corrects, and that it is the STATUS COLUMN rather than any time',
    '   comparison that prevents a BACKWARD correction from resending.',
    '8. Report where the logs land (docker logs, and unRAID\'s own retention',
    '   behaviour), and confirm nothing in them contains the token.',
  ].join('\n'), { label: 'ops:container+watchdog+backup', phase: 'Ops', schema: REPORT })
}

// -------------------------------------------------------------------- 6 REPORT

phase('Report')

const final = await agent([RULES, CONTEXT, '',
  'TASK: write ' + ROOT + '/docs/LIVE_VERIFY_REPORT.md -- the honest ledger of',
  'this deployment. You are the last agent. Make no Discord calls and change no',
  'code; you are writing the record.',
  '',
  'Inputs from this run:',
  '',
  'PREFLIGHT: ' + JSON.stringify(preOk, null, 2),
  '',
  'CONNECT: ' + JSON.stringify(connect, null, 2),
  '',
  'LIVE CHECKS: ' + JSON.stringify(live, null, 2),
  '',
  'DIAGNOSES: ' + JSON.stringify(diagnoses, null, 2),
  '',
  'OPS: ' + JSON.stringify(ops, null, 2),
  '',
  'Write the document with these sections:',
  '1. VERDICT up front, one line: is Marginalia live and trustworthy, live with',
  '   caveats, or not live. Do not bury this.',
  '2. A table of every live check with pass/partial/fail and one line of real',
  '   evidence each.',
  '3. WHAT A HUMAN MUST STILL DO, ordered, with the exact portal path or the',
  '   exact command. Include the two-member two-timezone confirmation, which no',
  '   agent can perform.',
  '4. CORRECTIONS TO THE DOCS. Anything this run measured that contradicts',
  '   docs/SPEC.md, docs/ENV.md, docs/HANDOFF.md, docs/HANDOFF.md,',
  '   docs/PORTAL_SETUP.md or deploy/README.md. Be specific: what was believed,',
  '   what is true, how you measured it. Settle the previously-open question of',
  '   whether timestamp markup and spoiler bars render inside embed slots. These',
  '   corrections are the most valuable output of the whole run -- flag clearly',
  '   that they belong edited back into those files, not stranded here.',
  '   Note especially: docs/ENV.md carries over from the FIRST build and',
  '   describes 22 modules and 30 commands. Its measurements hold, its',
  '   architecture does not. Say what you found.',
  '5. TICK OFF docs/HANDOFF.md\'s "NEVER RUN" list item by item: proven, still',
  '   unproven, or proven broken. That list was written as the work queue for',
  '   this run, so leaving an item unaddressed is itself a finding.',
  '6. KNOWN GAPS AND RISKS, ranked, each with its blast radius. Fold in any of',
  '   docs/HANDOFF.md\'s residual LOW findings this run touched.',
  '7. THE OPERATOR RUNBOOK: how to tell it is healthy, how to tell it is',
  '   running-but-not-scheduling (the heartbeat one-liner), where the logs are,',
  '   how to restart, how to restore a backup, how to roll back a bad deploy,',
  '   and the standing warning that the database must never move to /mnt/user.',
  '8. TOKEN HYGIENE: confirm the token never appeared in a log, a report, a',
  '   committed file, or shell history. If it did anywhere, say so plainly and',
  '   put "rotate the token" at the top of section 3.',
  '',
  'Be scrupulously accurate. If something was not tested, write NOT TESTED --',
  'never infer a pass. A confident wrong ledger will be trusted for months and',
  'is worse than an honest incomplete one.',
].join('\n'), { label: 'report:ledger', phase: 'Report', schema: REPORT })

return {
  mode: MODE,
  preflight: preOk,
  connect,
  live,
  diagnoses,
  ops,
  report: final,
  live_pass: live.filter((x) => x.result && x.result.status === 'pass').length,
  live_total: CHECKS.length,
}
